

export const ACTIONS = {
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    UPDATE_QUANTITY_ITEM_CART: 'UPDATE_QUANTITY_ITEM_CART',
    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
    RESET_CART: 'RESET_CART',
    SAVE_INFO_ORDER: 'SAVE_INFO_ORDER',
    INCREASE_QTY_ITEM_CART : 'INCREASE_QTY_ITEM_CART',
    DECREASE_QTY_ITEM_CART: 'DECREASE_QTY_ITEM_CART',
}