

export const ACTIONS = {
    ADD_CART: 'ADD_CART_ITEM',
    REMOVE_CART: 'CART_REMOVE_ITEM',
    RESET_CART: 'RESET_CART',
    SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS',
    SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD'
}