

export const ACTIONS = {
    ADD_CART: 'ADD_CART_ITEM',
    REMOVE_CART: 'CART_REMOVE_ITEM',
    RESET_CART: 'RESET_CART',
    SAVE_INFO_ORDER: 'SAVE_INFO_ORDER',
    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
}